# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# See docs at https://www.packer.io/docs/install/index.html
steps:
- name: 'gcr.io/cloud-builders/wget'
  args: [
    "https://releases.hashicorp.com/packer/${_PACKER_VERSION}/packer_${_PACKER_VERSION}_linux_amd64.zip",
    "https://github.com/YaleUniversity/packer-provisioner-goss/releases/download/${_PACKER_GOSS_VERSION}/packer-provisioner-goss-${_PACKER_GOSS_VERSION}-linux-amd64"
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/packer:${_PACKER_VERSION}',
        '-t', 'gcr.io/$PROJECT_ID/packer',
        '--build-arg', 'PACKER_VERSION=${_PACKER_VERSION}',
        '--build-arg', 'PACKER_VERSION_SHA256SUM=${_PACKER_VERSION_SHA256SUM}',
        '--build-arg', 'PACKER_GOSS_VERSION=${_PACKER_GOSS_VERSION}',
        '.']
substitutions:
  _PACKER_VERSION: 1.4.5
  _PACKER_VERSION_SHA256SUM: 30da8dab9c526a6d15b037e2234f6f12cf3accfad77eb2c130738ec1a54cab6d
  _PACKER_GOSS_VERSION: v0.3.0

images:
- 'gcr.io/$PROJECT_ID/packer:latest'
- 'gcr.io/$PROJECT_ID/packer:$_PACKER_VERSION'
tags: ['cloud-builders-community']
